### ISSUE TITLE
ResourceExhausted: cannot allocate memory

### ISSUE THREAD

**Issue by SemUijen** [microsoft/SynapseVSCode#54]
During building the image, the following error keeps ocurring:

ERROR: failed to solve: ResourceExhausted: process "/bin/sh -c conda install -c conda-forge pyspark==$SPARK_VERSION" did not complete successfully: cannot allocate memory

The error logs in Docker Desktop only shows the following:
dev_container_auto_added_stage_label
10/11
RUN conda install -c conda-forge pyspark==3.4.1
ERROR
21m 22s
Retrieving notices: ...working...done
Collecting package metadata (current_repodata.json): ...working...done
Solving environment: ...working...failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working...done
Solving environment: ...working...

**Comment by SemUijen** [comment]
This has been fixed by increasing memory allocation in the docker destop settings
but main by changing the conda as showin in issue #47

**Comment by Sarah-Hao** [comment]
@SemUijen  Hi, may I ask how much memory did you allocate? 
I am having the same issue running on a M4 chip Mac, and increasing memory allocation to 16GB still fails for me :(

**Comment by b-tsammons** [comment]
I am using WSL 2 as my docker backend. I have the Processor count set to 32, memory size set to 40gb (my system has 64gb) and swap set to 15gb yet I am still hitting `cannot allocate memory` 

I was able to fix it by changing line 30 of the docker file (.devcontainer/mariner/Dockerfile) from

RUN conda install -c conda-forge pyspark==$SPARK_VERSION

to

RUN pip install pyspark==$SPARK_VERSION
